### ISSUE TITLE
Exposed encryption password? Would like clarification please

### ISSUE THREAD

**Issue by Mathiaszero** [ClaytonIndustries/QuickSave#6]
Hello, I was looking at the documentation and I see for encryption, there is a section where you put your password.  Wouldn't this password be exposed, and render the encryption of your data pointless if a hacker could find the password?

**Comment by ClaytonIndustries** [comment]
Hi, the password would be present in your apps final output. So it's possible that a hacker could reverse engineer it. If that level of security is your concern then you should either have a backend system that provides the key or have the user type in a password
